name: serveTestData
description: Sample HTTP REST API with static JSON file as backend
homepage: https://devowl.de

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  path: ^1.6.2

dev_dependencies:
  pedantic: ^1.7.0
